version: '3'

services:
  web:
    image: liolegal/mysite:1.0.0
    build: ./web
    environment:
      - DJANGO_SUPERUSER_PASSWORD=1234
    command: bash -c "
      python manage.py createsuperuser && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3303:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql